name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test
        run: go test -v ./...

      - name: Build for Linux
        run: CGO_ENABLED=0 GOOS=linux go build .

      - name: Build for Windows
        run: CGO_ENABLED=0 GOOS=windows go build .

      - name: Build for MacOS
        run: CGO_ENABLED=0 GOOS=darwin go build .
